version: '3.8'

services:
  db:
    image: postgres:17
    container_name: megaton-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./backups:/backups
    ports:
      - "5432:5432"
    networks:
      - megaton-network

networks:
  megaton-network:
    driver: bridge