version: '3.8'

services:
  db:
    image: postgres:17
    container_name: tron-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tron-network


networks:
  tron-network:
    driver: bridge